version: '3.8'

services:
  biomedical-al:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app/src
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    
  jupyter:
    build: .
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./results:/app/results
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped