random_forest:
  n_estimators: 100
  random_state: 42
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  bootstrap: true
  
qbc:
  n_committee_members: 5
  base_learners:
    - RandomForest
    - ExtraTrees
    - GradientBoosting
    - LogisticRegression
    - KNN
  
  # Individual learner parameters
  random_forest:
    n_estimators: 100
    random_state: 42
    
  extra_trees:
    n_estimators: 100
    random_state: 42
    
  gradient_boosting:
    n_estimators: 100
    random_state: 42
    learning_rate: 0.1
    
  logistic_regression:
    solver: "lbfgs"
    max_iter: 1000
    random_state: 42
    
  knn:
    n_neighbors: 5
    weights: "uniform"

dimensionality_reduction:
  pca:
    variance_threshold: 0.90
    
  umap:
    n_neighbors: 28
    min_dist: 0.04
    spread: 1.0
    target_weight: 0.5
    metric: "euclidean"
    
  tsne:
    perplexity: 30
    learning_rate: 200
    n_iter: 1000
    
  lda:
    solver: "svd"